{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "gateway-proxy",
    "namespace": "default",
    "labels": {
      "app": "gateway-proxy"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "app": "gateway-proxy"
      }
    },
    "template": {
      "metadata": {
        "name": "gateway-proxy",
        "labels": {
          "app": "gateway-proxy"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "gateway-proxy",
            "image": "cfmicserver1.node/basegroup/gateway-proxy:1.0.0-SNAPSHOT",
            "resources": {},
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "Always",
            "securityContext": {
              "privileged": false
            }
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": "25%",
        "maxSurge": "25%"
      }
    },
    "revisionHistoryLimit": 10,
    "progressDeadlineSeconds": 600
  }
}